spring.datasource.url=jdbc:postgresql://localhost:5432/ai_os
spring.datasource.username=postgres
spring.datasource.password=Pp@06122003

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
jwt.secret=MySuperSecretKeyForAIOSProject12345678901234567890
jwt.expiration=86400000

gemini.api.key=YOUR_GEMINI_API_KEY
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent